OAI-30: Added string representations for report
openimis/openimis-be-claim_ai_quality_py pull request #14
Opened 2021-02-10 13:49 UTC by dborowiecki

TICKET: [OAI-30](https://openimis.atlassian.net/browse/OAI-30)

2021-02-10 16:19 UTC, dragos-dobre requested changes

2021-02-10 16:19 UTC, dragos-dobre commented on claim_ai_quality/report.py
> +        4: 'Chceked',
Please fix the spelling.

2021-02-11 08:07 UTC, dborowiecki commented on claim_ai_quality/report.py
> +        4: 'Chceked',
Fixed

2021-02-11 09:01 UTC, dragos-dobre approved these changes

2021-02-11 09:01 UTC, merged