OAI-29: Added claim bundle websocket client
openimis/openimis-be-claim_ai_quality_py pull request #4
Opened 2021-01-13 12:46 UTC by dborowiecki

TICKET: [OAI-29](https://openimis.atlassian.net/browse/OAI-29)

2021-01-14 20:11 UTC, dragos-dobre requested changes

2021-01-14 20:11 UTC, dragos-dobre commented on claim_ai_quality/communication_interface/aiServerCommunicationInterface.py
> +    async def _sustain_conneciton(self):
Please fix spelling.

2021-01-18 10:49 UTC, dborowiecki commented on claim_ai_quality/communication_interface/aiServerCommunicationInterface.py
> +    async def _sustain_conneciton(self):
Fixed

2021-01-18 15:40 UTC, dragos-dobre approved these changes

2021-01-18 15:41 UTC, merged